"""Phase 2: FieldGuard on-device classifier, trained on recorded Trace rows.

The provided dataset has no radio/IoT traffic (brief section 7) -- this
trains on data/traces/*.jsonl, one file per recording session, each line a
Trace row matching contracts/CONTRACT.md:
    {"ts":0,"node":"gateway","label":"normal","window_ms":5000,"hs_per_s":0,
     "hs_fail":0,"replay_rej":0,"auth_fail":0,"stale":0,"frag_timeout":0,
     "rssi_mean":-55.2,"rssi_var":3.1,"loss_pct":0.0,"jitter_ms":2.4}

A small decision tree (max_depth ~6) is exported straight to C so it can
run on the ESP32 with no runtime dependency: `int classify_window(const
float* f)`, where `f` holds FEATURE_ORDER's 10 features in order.
"""
import glob
import json
import os

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

# Must match, index for index, the order the gateway builds its feature vector
# in (firmware/lib/sentinel_proto/include/sentinel_proto/field_model.h,
# FIELD_MODEL_NUM_FEATURES = 10). window_ms is deliberately NOT a feature: it is
# the fixed 5000 ms detection window, so it carries no signal, and including it
# would shift every index by one against the firmware and read past its
# 10-float array. tests/test_feature_order_matches_firmware.py enforces this.
FEATURE_ORDER = [
    "hs_per_s", "hs_fail", "replay_rej", "auth_fail",
    "stale", "frag_timeout", "rssi_mean", "rssi_var", "loss_pct", "jitter_ms",
]
CLASSES = ["normal", "weak_link", "replay", "flood", "impersonation"]


def load_traces(trace_dir: str) -> pd.DataFrame:
    """One recording session per *.jsonl file; used as the eval group."""
    rows = []
    for path in sorted(glob.glob(os.path.join(trace_dir, "*.jsonl"))):
        session = os.path.splitext(os.path.basename(path))[0]
        with open(path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                d = json.loads(line)
                d["session"] = session
                rows.append(d)
    return pd.DataFrame(rows)


def train(trace_dir: str, max_depth: int = 6, seed: int = 42, classes: list = None):
    """Train on all sessions; evaluate leave-one-recording-session-out.

    `classes` overrides the production CLASSES list -- used by the
    synthetic-data test pipeline (ml/tests/) so a test run can never be
    mistaken for a real field-model result.

    Returns (clf, metrics). Raises ValueError if no trace files exist yet.
    """
    classes = classes or CLASSES
    df = load_traces(trace_dir)
    if df.empty:
        raise ValueError(f"no *.jsonl trace files found in {trace_dir} -- phase 2 waits on recorded traces")

    X = df[FEATURE_ORDER].values.astype(float)
    y = df["label"].map(classes.index).values
    sessions = df["session"].values

    clf = DecisionTreeClassifier(max_depth=max_depth, random_state=seed).fit(X, y)

    per_session = {}
    for s in sorted(set(sessions)):
        te_mask = sessions == s
        tr_mask = ~te_mask
        if len(set(y[tr_mask])) < 2 or te_mask.sum() == 0:
            continue
        m = DecisionTreeClassifier(max_depth=max_depth, random_state=seed).fit(X[tr_mask], y[tr_mask])
        pred = m.predict(X[te_mask])
        per_session[s] = dict(n=int(te_mask.sum()), acc=round(float((pred == y[te_mask]).mean()), 4))

    metrics = dict(
        rows=len(df),
        sessions=sorted(set(sessions)),
        class_counts=df["label"].value_counts().to_dict(),
        leave_one_session_out=per_session,
    )
    return clf, metrics


def _emit_node(node, tree, indent, classes):
    left, right = tree.children_left[node], tree.children_right[node]
    if left == -1 and right == -1:
        cls = int(np.argmax(tree.value[node][0]))
        return f"{indent}return {cls}; /* {classes[cls]} */\n"
    feat_idx = tree.feature[node]
    thr = tree.threshold[node]
    code = f"{indent}if (f[{feat_idx}] <= {thr:.6f}f) {{ /* {FEATURE_ORDER[feat_idx]} */\n"
    code += _emit_node(left, tree, indent + "    ", classes)
    code += f"{indent}}} else {{\n"
    code += _emit_node(right, tree, indent + "    ", classes)
    code += f"{indent}}}\n"
    return code


def export_c(clf: DecisionTreeClassifier, out_path: str, classes: list = None):
    """Write a self-contained header exposing classify_window(const float*)."""
    classes = classes or CLASSES
    body = _emit_node(0, clf.tree_, "    ", classes)
    lines = ["/* Auto-generated by sentinel_ml/field_model.py -- do not edit by hand. */",
             "#ifndef SENTINELMESH_FIELD_MODEL_H",
             "#define SENTINELMESH_FIELD_MODEL_H", ""]
    for i, c in enumerate(classes):
        lines.append(f"#define FIELD_CLASS_{c.upper()} {i}")
    lines.append("")
    lines.append("/* f[] must hold these " + str(len(FEATURE_ORDER)) + " features, in order:")
    for i, name in enumerate(FEATURE_ORDER):
        lines.append(f" *   f[{i}] = {name}")
    lines.append(" */")
    lines.append("static inline int classify_window(const float* f) {")
    lines.append(body.rstrip())
    lines.append("}")
    lines.append("")
    lines.append("#endif /* SENTINELMESH_FIELD_MODEL_H */")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
