/* Auto-generated by sentinel_ml/energygate.py -- do not edit by hand. */
/*
 * SIMULATED -- NOT A RESULT.
 * Trained on synthetic Trace rows from ml/tests/generate_synthetic_traces.py --hard
 * (overlapping classes, noise, 3% label noise), not on real board recordings. It
 * encodes our own assumptions about attack traffic. Replace with the output of
 * `make energygate` (ml/README.md, phase 3) once real traces exist in ml/data/traces/.
 * Never present its accuracy as a measured result.
 */
#ifndef SENTINELMESH_ENERGYGATE_H
#define SENTINELMESH_ENERGYGATE_H

/* f[] must hold these 8 features, in order:
 *   f[0] = hs_per_s
 *   f[1] = hs_fail
 *   f[2] = rssi_mean
 *   f[3] = rssi_var
 *   f[4] = loss_pct
 *   f[5] = dup_pct
 *   f[6] = frag_complete_pct
 *   f[7] = battery_pct
 */
static inline float energygate_score(const float* f) {
    if (f[1] <= 2.500000f) { /* hs_fail */
        if (f[5] <= 8.302421f) { /* dup_pct */
            if (f[0] <= 1.395645f) { /* hs_per_s */
                if (f[5] <= 6.275391f) { /* dup_pct */
                    if (f[1] <= 1.500000f) { /* hs_fail */
                        return 0.958389f;
                    } else {
                        return 0.659091f;
                    }
                } else {
                    if (f[4] <= 2.566401f) { /* loss_pct */
                        return 0.074074f;
                    } else {
                        return 1.000000f;
                    }
                }
            } else {
                return 0.095238f;
            }
        } else {
            if (f[4] <= 2.606249f) { /* loss_pct */
                if (f[0] <= 0.213350f) { /* hs_per_s */
                    return 0.050000f;
                } else {
                    if (f[3] <= 1.198887f) { /* rssi_var */
                        return 0.035714f;
                    } else {
                        return 0.000000f;
                    }
                }
            } else {
                return 0.500000f;
            }
        }
    } else {
        if (f[2] <= -65.549767f) { /* rssi_mean */
            return 0.350000f;
        } else {
            if (f[3] <= 9.654250f) { /* rssi_var */
                if (f[0] <= 0.684953f) { /* hs_per_s */
                    if (f[5] <= 1.136696f) { /* dup_pct */
                        return 0.000000f;
                    } else {
                        return 0.130435f;
                    }
                } else {
                    if (f[7] <= 41.011089f) { /* battery_pct */
                        return 0.023256f;
                    } else {
                        return 0.001678f;
                    }
                }
            } else {
                return 0.090909f;
            }
        }
    }
}

#endif /* SENTINELMESH_ENERGYGATE_H */
